### ISSUE TITLE
dumpbin showing that LargeAddressAware was not set

### ISSUE THREAD

**Issue by rollsch** [KirillOsenkov/LargeAddressAware#6] opened 2019-11-14 04:00 UTC
"Also make sure that the .targets file from the NuPkg is included in your build. To do this, build your project using http://msbuildlog.com and search for "LargeAddressAware" in the structured log."

I have run this and searched for it but I'm not sure exactly what I am searching for. It shows that it is in my csproj files however I already knew this as I added it myself.

What exactly should be shown in the log to indicate it ran successfully, also in my case where it is not setting the flag, what should I look for to debug why it was not set?

If I manually run editbin it sets it correctly on my exe.

**Comment by KirillOsenkov** [comment] 2019-11-14 04:27
Have you added this to your .csproj:

```
  <PropertyGroup>
    <LargeAddressAware>true</LargeAddressAware>
  </PropertyGroup>
```

Search for `$target SetLargeAddressAware` in the binlog viewer

**Comment by rollsch** [comment] 2019-11-14 05:12
Yes I have that in my csproj. I tried putting it in lots of different places.

When I ran MSBuildStructuredLogSetup.exe and compiled my project the search just showed me the csproj files again then a bunch of "LargeAddressAware = true" in the log and nothing.

Is there something specific I should see that would indicate it is actually editing the PE?

Thanks for the quick reply.

**Comment by KirillOsenkov** [comment] 2019-11-14 06:02
Search for `$target SetLargeAddressAware` in the binlog viewer - if you don't see a target in the search results it means it didn't run.

If you see the target, it means it ran so we'll have to dig in deeper.

**Comment by KirillOsenkov** [comment] 2019-11-14 06:04
Have you verified that your project is compiling as x86, and not AnyCPU by any chance? Also, if you simply compile to AnyCPU and set Prefer32Bit to true in MSBuild, then it would be equivalent to having a 32-bit app with LargeAddressAware == true. Technically I'd recommend that instead of an actual x86 app where you have to manually set the flag.

**Comment by rollsch** [comment] 2019-11-14 07:28
"simply compile to AnyCPU and set Prefer32Bit to true in MSBuild, then it would be equivalent to having a 32-bit app with LargeAddressAware == true"

I had absolutely no idea that was possible. Sounds easier!

**Comment by Adiel-Sharabi** [comment] 2019-11-24 08:59
Hi, 
Somehow I also did all the instructions and had the target in logs, and the project is set to exe, x86, but still the dumpbin missing header. 
Any ideas?

**Comment by jwittner** [comment] 2020-06-13 04:19
>  if you simply compile to AnyCPU and set Prefer32Bit to true in MSBuild, then it would be equivalent to having a 32-bit app with LargeAddressAware == true.

I have an Any CPU app that functions correctly if I ran editbin to set the LargeAddressAware flag. I was attempting to switch to this package and found that the flag was no longer set. Realizing that the targets files only applies the change if targeting x86 I started googling and found this issue.

I tried the above settings for Prefer 32-bit, but alas my generated application is not marked as "Application can handle large (>2GB) addresses" with dumpbin. With these settings unfortunately my application still breaks the memory limit. If I editbin and apply the flag, no problems. =(

**Comment by KirillOsenkov** [comment] 2020-06-14 02:47
@jwittner if you create a new Console Application in Visual Studio and add this NuGet package, does the problem reproduce?

Have you followed the steps described in the readme? https://github.com/KirillOsenkov/LargeAddressAware/blob/master/README.md
Have you obtained an msbuild.binlog file, opened it in the viewer (from https://msbuildlog.com)  and ensured that the target is actually run?

What information can you share to help me reproduce the issue? Can you share the source project? The resulting binary? Can you share the msbuild.binlog file? Feel free to e-mail at Kirill dot Osenkov at microsoft.

Have you tried diffing the binary that you get after editbin with the binary you obtained after the build? You can use any hex editor, or in absence of that, I wrote a tool to dump a binary into bytes: https://github.com/KirillOsenkov/CodeCleanupTools/tree/master/bin2hex

**Comment by KirillOsenkov** [comment] 2020-06-14 02:52
When you inspect the .binlog you should see the task being invoked:
![image](https://user-images.githubusercontent.com/679326/84583642-73afbb00-adaf-11ea-99fc-ca5a61b7573b.png)

**Comment by KirillOsenkov** [comment] 2020-06-14 02:53
This is a sample project that I used:

```msbuild
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <PlatformTarget>x86</PlatformTarget>
    <LargeAddressAware>true</LargeAddressAware>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LargeAddressAware" Version="1.0.4" />
  </ItemGroup>

</Project>
```

**Comment by jwittner** [comment] 2020-06-15 19:18
I had followed the instructions in the README, but not yet used the MSBuild logging tools - which, now that I have, I can say are totally awesome so thank you for them too!

I believe I've found my issue. I'm leveraging [Fody ](https://github.com/Fody/PropertyChanged) as well which does some code generation and weaving. It appears from the logs that LargeAddressAware was running after CoreCompile and modifying the executable (the message above was included in the logs), but then Fody was recreating the executable and losing the flag. If I modify the LAW targets to run after the Fody targets then my exe is appropriately marked with "Application can handle large (>2GB) addresses". 

Any chance you've seen this kind of order of operations issues before? Any good recommendation for how to control this order when the targets are included in nuget packages?

**Comment by KirillOsenkov** [comment] 2020-06-15 19:34
Ah, yes, that would explain it. You can control the target build order via some combination of `BeforeTargets`, `AfterTargets` and `DependsOnTargets`. You can read more about it here:
https://docs.microsoft.com/en-us/visualstudio/msbuild/target-build-order?view=vs-2019

You probably want to set the Fody target in here:
https://github.com/KirillOsenkov/LargeAddressAware/blob/7c4c68ebf5bd2df96e7492aaca006a3dea93a023/SetLargeAddressAware/LargeAddressAware.targets#L22

to make sure LargeAddressAware runs after Fody. Not sure what's the best way for you to do it, perhaps just copy the entire target body (if you place it "after" the target being included from NuGet it will override).

**Comment by jwittner** [comment] 2020-06-15 19:36
Yep, that's what I was changing. I've forked your branch and am adding a new overridable property `LargeAddressAwareAfterTargets` which will default to `CoreCompile` so that people can control this order from their csproj. Think you'd be keen to take that change? I'm testing it out now and can make a PR shortly.

**Comment by jwittner** [comment] 2020-06-15 19:39
I'm wondering too about changing the test in the targets: `'$(PlatformTarget)' == 'x86'` to be `'$(PlatformTargetAsMSBuildArchitecture)' == 'x86'`, but I'm less certain of that one. My issue is that my PlatformTarget is AnyCPU so unless I modify the test the Target doesn't run.

Not sure yet at the cause of why "AnyCPU/Prefer 32-Bit" isn't resulting in a binary marked as LargeAddressAware for me if I don't use this package, which, correct me if I'm wrong, it seems like you believe should be the case right?

**Comment by KirillOsenkov** [comment] 2020-06-15 20:06
If you're building as AnyCPU, the binary will use all 4GB already when running as a 32-bit process, so this flag is not necessary.

**Comment by KirillOsenkov** [comment] 2020-06-15 20:07
Thanks, I've made the same change:
https://github.com/KirillOsenkov/LargeAddressAware/commit/07192e39e34d0fa1701780fc0974b039e140644a

Published in NuGet 1.0.5:
https://www.nuget.org/packages/LargeAddressAware/1.0.5

**Comment by KirillOsenkov** [comment] 2020-06-15 20:16
I think I'm going to close this issue then, and if someone is still having issues I'm going to ask for a .binlog that shows whether the target ran and if so, when. It's likely that if you're using some post-compile IL rewriting it will stomp over the large address aware bit as we have seen in this instance.

**Closed as completed by KirillOsenkov** 2020-06-15 20:16 UTC

**Comment by rollsch** [comment] 2020-06-16 02:50
FYI my problem was due to using ILMerge in a post build script that I had completely forgotten about. So it was also user error.

**Comment by KirillOsenkov** [comment] 2020-06-16 02:54
Nice, thanks for the follow up.

**Comment by Adiel-Sharabi** [comment] 2020-09-13 10:57
Hi, My problem was regarding a PostSharp phase. 
I've changed the "SetLargeAddressAware" to AfterTargets="PostSharp" and it works for me.
